
services:
  flask:
    build:
      context: .
    ports:
      - "6969:6969"
    depends_on:
      - ollama
    volumes:
      - .:/app  # optional, sync code
    environment:
      - CONFIG_PATH=config.yaml

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persistent model storage

volumes:
  ollama_models: