
services:
  flask:
    build:
      context: .
    ports:
      - "6749:6749"
    depends_on:
      - ollama
    volumes:
      - .:/app  # optional, sync code
    environment:
      - CONFIG_PATH=config.yaml

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persistent model storage
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
volumes:
  ollama_models: